# Generated by Django 3.0.5 on 2020-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetescontainer',
            name='image_name',
            field=models.CharField(db_index=True, default='debian', help_text='Properly qualified image name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='average_cpu_usage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average PIT CPU units consumed', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='average_mem_usage',
            field=models.IntegerField(blank=True, help_text='Average PIT bytes consumed', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='cpu_usage_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average cpu usage * seconds live', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='mem_usage_seconds',
            field=models.IntegerField(blank=True, help_text='Average mem usage * seconds live', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='object_status',
            field=models.CharField(blank=True, help_text='status of the object in Kubernetes', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='average_cpu_usage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average PIT CPU units consumed', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='average_mem_usage',
            field=models.IntegerField(blank=True, help_text='Average PIT bytes consumed', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='cpu_usage_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average cpu usage * seconds live', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='mem_usage_seconds',
            field=models.IntegerField(blank=True, help_text='Average mem usage * seconds live', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='object_status',
            field=models.CharField(blank=True, help_text='status of the object in Kubernetes', max_length=128, null=True),
        ),
    ]
