# Generated by Django 3.0.3 on 2020-02-21 00:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
