# Generated by Django 3.0.3 on 2020-02-21 00:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0002_auto_20200221_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='kubernetes-object', max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('labels', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('annotations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('api_version', models.CharField(default='v1', max_length=16)),
                ('kind', models.CharField(default='Service', max_length=16)),
                ('port', models.IntegerField(default=80)),
                ('backoff_limit', models.IntegerField(default=3)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster')),
                ('pod_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesPodTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
