# Generated by Django 3.0.5 on 2020-04-03 18:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0002_auto_20200403_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubernetesconfigmap',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetescontainer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesdeployment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesingress',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesjob',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesnamespace',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetespodtemplate',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesservice',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesvolume',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='kubernetesvolumemount',
            name='deleted',
        ),
        migrations.AddField(
            model_name='kubernetesconfigmap',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetescontainer',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesingress',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesnamespace',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetespodtemplate',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesservice',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesvolume',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AddField(
            model_name='kubernetesvolumemount',
            name='removed',
            field=models.DateTimeField(blank=True, help_text='Time when object is removed from cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesconfigmap',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='kubernetescontainer',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetescontainer',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetescontainer',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetescontainer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='api_version',
            field=models.CharField(default='v1', help_text='API version used to deploy child object.', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='kind',
            field=models.CharField(help_text='String representation of Kubernetes object kind', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='namespace',
            field=models.ForeignKey(help_text='Live namespace the object is associated with.', on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='port',
            field=models.IntegerField(default=80, help_text='Port object will expose'),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='api_version',
            field=models.CharField(default='v1', help_text='API version used to deploy child object.', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='kind',
            field=models.CharField(help_text='String representation of Kubernetes object kind', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='namespace',
            field=models.ForeignKey(help_text='Live namespace the object is associated with.', on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='port',
            field=models.IntegerField(default=80, help_text='Port object will expose'),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='api_version',
            field=models.CharField(default='v1', help_text='API version used to deploy child object.', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='kind',
            field=models.CharField(help_text='String representation of Kubernetes object kind', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='namespace',
            field=models.ForeignKey(help_text='Live namespace the object is associated with.', on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='port',
            field=models.IntegerField(default=80, help_text='Port object will expose'),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetespodtemplate',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='annotations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary store equivalent to Annotations in Kubernetes API', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='api_version',
            field=models.CharField(default='v1', help_text='API version used to deploy child object.', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='kind',
            field=models.CharField(help_text='String representation of Kubernetes object kind', max_length=16),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary store equivalent to Labels in Kubernetes API'),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='namespace',
            field=models.ForeignKey(help_text='Live namespace the object is associated with.', on_delete=django.db.models.deletion.CASCADE, to='django_kubernetes_manager.KubernetesNamespace'),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='port',
            field=models.IntegerField(default=80, help_text='Port object will expose'),
        ),
        migrations.AlterField(
            model_name='kubernetesvolume',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesvolume',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesvolume',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesvolume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kubernetesvolumemount',
            name='cluster',
            field=models.ForeignKey(help_text='ForeignKey to TargetCluster object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_kubernetes_manager.TargetCluster'),
        ),
        migrations.AlterField(
            model_name='kubernetesvolumemount',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Pass in extra parameters here.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesvolumemount',
            name='deployed',
            field=models.DateTimeField(blank=True, help_text='Time when object is applied to cluster.', null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesvolumemount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID Auto field.', primary_key=True, serialize=False),
        ),
    ]
