# Generated by Django 3.0.3 on 2020-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0004_auto_20200222_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='kuid',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesingress',
            name='kuid',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='kuid',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesservice',
            name='kuid',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
