# Generated by Django 3.0.3 on 2020-02-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0005_auto_20200226_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KubernetesTelemetryMixin',
        ),
    ]
