# Generated by Django 3.0.3 on 2020-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0006_delete_kubernetestelemetrymixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='average_cpu_usage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='average_mem_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='cpu_usage_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='mem_usage_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='object_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='average_cpu_usage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='average_mem_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='cpu_usage_seconds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='mem_usage_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='object_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
