# Generated by Django 3.0.3 on 2020-02-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0007_auto_20200226_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kubernetescontainer',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesdeployment',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesingress',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesjob',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetespodtemplate',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesservice',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesvolume',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RenameField(
            model_name='kubernetesvolumemount',
            old_name='created',
            new_name='deployed',
        ),
        migrations.RemoveField(
            model_name='kubernetescontainer',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesdeployment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesingress',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesjob',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetespodtemplate',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesservice',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesvolume',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kubernetesvolumemount',
            name='modified',
        ),
    ]
