# Generated by Django 3.0.3 on 2020-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0008_auto_20200226_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesdeployment',
            name='kuid',
            field=models.CharField(blank=True, help_text="Object's UID in the cluster", max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesingress',
            name='kuid',
            field=models.CharField(blank=True, help_text="Object's UID in the cluster", max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesjob',
            name='kuid',
            field=models.CharField(blank=True, help_text="Object's UID in the cluster", max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesservice',
            name='kuid',
            field=models.CharField(blank=True, help_text="Object's UID in the cluster", max_length=48, null=True),
        ),
    ]
