# Generated by Django 3.0.3 on 2020-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0009_auto_20200226_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='namespace',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='kubernetesingress',
            name='namespace',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='namespace',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='kubernetesservice',
            name='namespace',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
