# Generated by Django 3.0.4 on 2020-03-10 15:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0013_auto_20200228_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetcluster',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Configuration data stored as an encrypted blob in the database', null=True),
        ),
    ]
