# Generated by Django 3.0.4 on 2020-03-10 16:07

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_kubernetes_manager', '0015_auto_20200310_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetescontainer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesdeployment',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesingress',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesjob',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetespodtemplate',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesservice',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesvolume',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='kubernetesvolumemount',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='targetcluster',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug'),
        ),
    ]
