version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  skip:
    steps:
      - run:
          command: |
            exit 0
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python setup.py sdist bdist_wheel
          name: Build packages
      - run:
          command: |
            python -m twine upload --repository-url https://upload.pypi.org/legacy/ -u $PYPI_USER -p $PYPI_PASS dist/*
          name: Publish to PyPi
workflows:
  main:
    jobs:
      - skip:
          filters:
            branches: 
              only: master
      - build:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
