# Generated by Django 3.0.5 on 2020-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubernetescontainer',
            name='volume_mount',
        ),
        migrations.RemoveField(
            model_name='kubernetespodtemplate',
            name='primary_container',
        ),
        migrations.RemoveField(
            model_name='kubernetespodtemplate',
            name='secondary_container',
        ),
        migrations.RemoveField(
            model_name='kubernetespodtemplate',
            name='volume',
        ),
        migrations.AddField(
            model_name='kubernetescontainer',
            name='volume_mounts',
            field=models.ManyToManyField(blank=True, null=True, to='kubernetes_manager.KubernetesVolumeMount'),
        ),
        migrations.AddField(
            model_name='kubernetespodtemplate',
            name='containers',
            field=models.ManyToManyField(to='kubernetes_manager.KubernetesContainer'),
        ),
        migrations.AddField(
            model_name='kubernetespodtemplate',
            name='volumes',
            field=models.ManyToManyField(blank=True, null=True, to='kubernetes_manager.KubernetesVolume'),
        ),
    ]
